name: Test Google Chat Notification

on:
  workflow_dispatch:

jobs:
  test_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Notification
        uses: benjlevesque/slack-to-google-chat@v1
        with:
          webhook_url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          text: "Test notification from GitHub Actions"
