name: Google Chat Notification

on:
  push:
    branches:
      - main # or your branch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Google Chat Notification
        uses: google-github-actions/chat-message@v1
        with:
          webhook_url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          text: |
            **New Push to ${{ github.repository }}**
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Message: ${{ github.event.head_commit.message }}
            Author: ${{ github.event.head_commit.author.name }}
