name: Send Message to Google Chat

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  google-chat-action:
    name: Google Chat GitHub Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Notify Google Chat
        if: ${{ always() }}
        uses: tporret/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: '${{ job.status }}'
