name: Google Chat Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
          WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Ensures the repository code is available

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify the Node.js version required for your script

      - name: Install dependencies
        run: npm install
        working-directory: scripts # Adjust if your `package.json` is in a different directory

      - name: Install axios
        run: npm install axios
        working-directory: scripts # Ensure axios is installed in the correct directory

      - name: Send Google Chat Notification
        if: always()
        run: node scripts/index.js
          
